name: "Bindgen"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  bindgen-ast-job:
    name: "Bindgen AST"
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows, os: windows-2022, rid: win }
          - { name: macOS, os: macos-latest, rid: osx }
          - { name: Linux, os: ubuntu-latest, rid: linux }

    steps:
      - name: Install .NET 8.0
        if: runner.os == 'macOS'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: "Clone Git repository"
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: "Install c2ffi"
        shell: bash
        run: dotnet tool install --global bottlenoselabs.c2ffi.Tool

      - name: "Read C code: Linux dependencies"
        if: runner.os == 'Linux'
        run: sudo apt-get install gcc-aarch64-linux-gnu

      - name: "Read C code: extract ${{ matrix.platform.rid }}"
        shell: bash
        run: cd ./bindgen && ./extract.sh
        
      - name: "Show extracted files"
        shell: bash
        run: |
          echo "PWD=$(pwd)"
          ls -la ./bindgen || true
          ls -la ./bindgen/ast || true
          ls -la ./ast || true
          find ./bindgen -maxdepth 4 -type f -print || true
          find . -maxdepth 3 -type f -name "*.json" -print || true

      - name: "Upload C code platform abstract syntax trees (per-platform)"
        uses: actions/upload-artifact@v4
        with:
          name: "ffi-${{ matrix.platform.rid }}"
          path: "./bindgen/ffi/**"
          if-no-files-found: error

  bindgen-cross-platform-ast-job:
    name: "Bindgen AST cross-platform"
    needs: [bindgen-ast-job]
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v2
        with:
          submodules: "false"

      - name: "Download C code platform abstract syntax trees (win)"
        uses: actions/download-artifact@v4
        with:
          name: "ffi-win"
          path: "./bindgen/ffi"

      - name: "Download C code platform abstract syntax trees (osx)"
        uses: actions/download-artifact@v4
        with:
          name: "ffi-osx"
          path: "./bindgen/ffi"

      - name: "Download C code platform abstract syntax trees (linux)"
        uses: actions/download-artifact@v4
        with:
          name: "ffi-linux"
          path: "./bindgen/ffi"

      - name: "Install c2ffi"
        shell: bash
        run: dotnet tool install --global bottlenoselabs.c2ffi.Tool

      - name: "Generate cross-platform AST"
        shell: bash
        run: cd ./bindgen && ./merge.sh

      - name: "Upload cross-platform AST"
        uses: actions/upload-artifact@v4
        with:
          name: "ast-cross-platform"
          path: "./bindgen/x-ffi/ffi-cross-platform.json"

  bindgen-cs-job:
    name: "Bindgen C#"
    needs: [bindgen-cross-platform-ast-job]
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v2
        with:
          submodules: "false"

      - name: "Download C code cross-platform abstract syntax tree"
        uses: actions/download-artifact@v4
        with:
          name: "ast-cross-platform"
          path: "./bindgen/x-ffi"

      - name: "Install C2CS"
        shell: bash
        run: dotnet tool install --global bottlenoselabs.C2CS.Tool

      - name: "Generate C# code"
        shell: bash
        run: cd ./bindgen && ./generate.sh

      - name: "Upload generated C# code"
        uses: actions/upload-artifact@v4
        with:
          name: "bindgen-cs"
          path: "./src/cs/production/Tracy/Generated"
